platform :ios,'9.0'
use_frameworks!

flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'native' do
  
  install_all_flutter_pods(flutter_application_path)
  
end


